### ISSUE TITLE
Flow running on a remote host BADREQ

### ISSUE THREAD

**Issue by alekhos** [nextcloud/flow#8]
We have a remote setup with TLS (Nextcloud and docker-app-proxy) running in different VMs. Daemon and Test Deploy worked ok, all other ExApps working as well.
After installation, all interactions with Flow returns a 400 error. It doesn´t even load the icon at the Nextcloud bar. 
HA Proxy logs on the remote server show:
` ex_apps~ ex_apps/<NOSRV> -1/-1/-1/-1/0 400 0 - - PR-- 1/1/0/0/0 0/0 "<BADREQ>"`
Upon further exploration we detected that Flow app is running on 0.0.0.0:8000 instead of 127.0.0.1 like the others apps.
It seems like a problem between the HA Proxy conf and the port of the Flow app. 
Because of the auto installation process of the external app, we have no access to it´s build/run configurations. 
We appreciate any insights into this.

**Comment by bigcat88** [comment]
Windmill itself is listen on port 8000.
ExApp listens to the port that will be in the port column in the oc_ex_apps table in the cloud.

I think you need the port that ExApp listens to, and not Windmill itself.

I'll add a diagram of how it all works in a few days, I'll start working on it now

**Comment by bigcat88** [comment]
@alekhos were you able to fix the issue or maybe you have any further additional information regarding this?
